import os
import json
from ml_engine.inference import get_intent_response

PROFILE_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "profile.json")

def get_response(user_input: str) -> str:
    """
    Get a response from the NLP engine based on user input.
    
    Args:
        user_input (str): The input message from the user.
        
    Returns:
        str: The response generated by the NLP engine.
    """
   # 1. Asking which intent the user input corresponds to

    tag, raw_response = get_intent_response(user_input)

    # 2. Loading profile data
    with open(PROFILE_PATH, "r", encoding="utf-8") as f:
        profile = json.load(f)

    info = profile.get("personal_info", {})
    interests = profile.get("interests", {})
    bot_cfg = profile.get("bot_config", {})


    skills_str = ", ".join(profile.get("tech_stack", []))
    hobbies_str = ", ".join(profile.get("interests", {}).get("hobbies", []))
    books_str = ", ".join(profile.get("interests", {}).get("favorite_books", []))

   # Projekte aufbereiten (Name + Tech Stack)
    project_list = []
    for p in profile.get("projects", []):
        p_tech = ", ".join(p.get("tech_stack", []))
        project_list.append(f"{p['name']} ({p_tech})")
    
    projects_str = " | ".join(project_list) if project_list else "Momentan keine Projekte gelistet."


    # 3. Formatting the response with profile data
    try:
        final_response = raw_response.format(
            # Profil-Basis-Infos
            bot_name=bot_cfg.get("bot_name", "Portfolio-Bot"),
            greeting_msg=bot_cfg.get("greeting_msg", "Hallo!"),
            farewell_msg=bot_cfg.get("farewell_msg", "Bis bald!"),
            thanks_msg=bot_cfg.get("thanks_msg", "Gern geschehen!"),
            
            name=profile["personal_info"]["full_name"],
            role=profile["personal_info"]["role"],
            location=profile["personal_info"]["location"],
            bio=profile["personal_info"]["bio"],
            
            # Kontakt-Infos
            email=profile["personal_info"]["email"],
            linkedin=profile["personal_info"]["linkedin"],
            github=profile["personal_info"]["github"],
            
            # Listen (als formatierte Strings)
            skills=skills_str,
            hobbies=hobbies_str,
            favorite_books=books_str,
            projects=projects_str
        )


    except KeyError as e:
        print(f"Fehlender Platzhalter in der Antwort: {e}")
        final_response = raw_response  # Fallback zur rohen Antwort

    return final_response
