import os
import json
from ml_engine.inference import get_intent_response

PROFILE_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "profile.json")

def get_response(user_input: str) -> str:
    """
    Get a response from the NLP engine based on user input.
    
    Args:
        user_input (str): The input message from the user.
        
    Returns:
        str: The response generated by the NLP engine.
    """
   # 1. Asking which intent the user input corresponds to

    tag, raw_response = get_intent_response(user_input)

    # 2. Loading profile data
    with open(PROFILE_PATH, "r", encoding="utf-8") as f:
        profile = json.load(f)

    # 3. Formatting the response with profile data
    try:
        final_response= raw_response.format(
            name=profile["profile"]["name"],
            role=profile["profile"]["role"],
            location=profile["profile"]["location"],
            skills=", ".join(profile["skills"]),
            email=profile["profile"]["contact"]["email"]
            # Füge hier alle weiteren Platzhalter hinzu
        )


    except KeyError as e:
        print(f"Fehlender Platzhalter in der Antwort: {e}")
        final_response = raw_response  # Fallback zur rohen Antwort

    return final_response
